### ISSUE TITLE
How to access the API

### ISSUE THREAD

**Issue by stychu** [bnb-chain/BEPs#106]
How can I consume the API??
I would like to retrieve the data of the account addresses (balance/tokens held/amounts) in the NodeJs app.
Can someone point me?

**Comment by mtl1979** [comment]
I use web3js with NodeJS. Depending on if you use testnet or mainnet, the RPC endpoint is different.

mainnet: https://bsc-dataseed.binance.org/
testnet: https://data-seed-prebsc-1-s1.binance.org:8545/

Some API methods require WebSockets, so just replace "https" with "wss" in the RPC address and create new WebSocket provider.

For example:

`var web3 = new Web3("https://bsc-dataseed.binance.org/");`

or 

`var web3 = new Web3(new Web3.providers.WebsocketProvider("wss://bsc-dataseed.binance.org/"));`

After that you can just look up in the API documentation to see how to pass parameters to the `web3` object and its functions.

**Comment by dongdong-gogogo** [comment]
> I use web3js with NodeJS. Depending on if you use testnet or mainnet, the RPC endpoint is different.
> 
> mainnet: https://bsc-dataseed.binance.org/ testnet: https://data-seed-prebsc-1-s1.binance.org:8545/
> 
> Some API methods require WebSockets, so just replace "https" with "wss" in the RPC address and create new WebSocket provider.
> 
> For example:
> 
> `var web3 = new Web3("https://bsc-dataseed.binance.org/");`
> 
> or
> 
> `var web3 = new Web3(new Web3.providers.WebsocketProvider("wss://bsc-dataseed.binance.org/"));`
> 
> After that you can just look up in the API documentation to see how to pass parameters to the `web3` object and its functions.

Hello, I would like to ask what you mean when you say that some methods require WebSocket?

**Comment by mtl1979** [comment]
> Hello, I would like to ask what you mean when you say that some methods require WebSocket?

WebsocketProvider is used when you "subscribe" to large amount of data, like monitoring contract event logs. It's a lot faster that way, as less data needs to be transferred. The "normal" provider needs to transfer big header every time data is requested and it always needs to know how much data will be returned... WebsocketProvider can incrementally return more data.

**Comment by dongdong-gogogo** [comment]
> > Hello, I would like to ask what you mean when you say that some methods require WebSocket?
> 
> WebsocketProvider is used when you "subscribe" to large amount of data, like monitoring contract event logs. It's a lot faster that way, as less data needs to be transferred. The "normal" provider needs to transfer big header every time data is requested and it always needs to know how much data will be returned... WebsocketProvider can incrementally return more data.

thank you for your reply

**Comment by rondales** [comment]
> How can I consume the API?? I would like to retrieve the data of the account addresses (balance/tokens held/amounts) in the NodeJs app. Can someone point me?

**Comment by mtl1979** [comment]
> > How can I consume the API?? I would like to retrieve the data of the account addresses (balance/tokens held/amounts) in the NodeJs app. Can someone point me?

This repository is about BEPs (Binance Chain Evolution Proposal)... We are not giving everyone detailed instructions about how to read API documentation as it would be off-topic.
