### ISSUE TITLE
Slash rule for candidate validator should be tougher than ordinary ones

### ISSUE THREAD

**Issue by 48ClubIan** [bnb-chain/BEPs#144]
According to https://github.com/bnb-chain/BEPs/blob/master/BEP131.md ,  

> On the other hand, all the slash rules also work on Candidate validators to ensure the malicious or negative behaviors from Candidates will be punished.

Since candidates are less likely to seal new blocks, thus less likely to reach slash threshold. 

Assuming an ordinary validator will be jailed after 150 slashed i.e. 2.5 hours -ish downtime, and BEP131 was deployed as MaxNumOfCandidates= 20 and MaxNumOfWorkingCandidates = 2, we will come to the situation that a candidate validator will be jailed after around 2.5*20/2 = 25 hours downtime.

That's almost a whole day, which means a candidate validator will never be slashed because of downtime.

**Comment by brilliant-lx** [comment]
Would close this issue, as BEP-131 has already been on mainnet since Jun 22nd 2022, one and half year passed.

**Comment by Rubens1969** [comment]
***@***.***
