### ISSUE TITLE
eth_sendRawTransaction method is succsess but transaction doesn't exist

### ISSUE THREAD

**Issue by IhorStasiv** [bnb-chain/BEPs#158]
{
          "id":1,
          "jsonrpc":"2.0",
          "method":"eth_sendRawTransaction",
          "params": ["0xf8ae84307836668512a05f200082dba494b84cbbf09b3ed388a45cd875ebba41a20365e6e780b844a9059cbb000000000000000000000000c3f069f88af54d17dd025538d532dd72ca9a166600000000000000372c3030302c3030302c3030302c3030302c3030302c3030308194a0830ae458deacbf377c1c205ae736aa70299d2b20f009edeb288f0eb313155d3ba006dcde67ec5d6347acc778f0816449192400255ced945f0437f587be979b5edc"]
      }
i'm trying to send a BitShiba token, I used to get a lot of errors and I could work with it somehow, but now I'm getting

          {
            "jsonrpc": "2.0",
            "id": 1,
            "result": "0xc852c10c4ccc4daa5b9916d49f68f56ff4922b01c0f49cae0af3749684358c1c"
          }

and this confuses me, because it is success but the transaction itself does not exist, and the tokens are not sent, what to do about it?

**Comment by Tyufgh** [comment]
> ```
>   {
>       "id":1,
>       "jsonrpc":"2.0",
>       "method":"eth_sendRawTransaction",
>       "params": ["0xf8ae84307836668512a05f200082dba494b84cbbf09b3ed388a45cd875ebba41a20365e6e780b844a9059cbb000000000000000000000000c3f069f88af54d17dd025538d532dd72ca9a166600000000000000372c3030302c3030302c3030302c3030302c3030302c3030308194a0830ae458deacbf377c1c205ae736aa70299d2b20f009edeb288f0eb313155d3ba006dcde67ec5d6347acc778f0816449192400255ced945f0437f587be979b5edc"]
>   }
> ```
> 
> i'm trying to send a BitShiba token, I used to get a lot of errors and I could work with it somehow, but now I'm getting
> 
> ```
>       {
>         "jsonrpc": "2.0",
>         "id": 1,
>         "result": "0xc852c10c4ccc4daa5b9916d49f68f56ff4922b01c0f49cae0af3749684358c1c"
>       }
> ```
> 
> and this confuses me, because it is success but the transaction itself does not exist, and the tokens are not sent, what to do about it?

**Comment by Tyufgh** [comment]
Кра
