### ISSUE TITLE
0x59576Fb376F1FEaEdb9c768A724D8C06304538f5

### ISSUE THREAD

**Issue by Anastasia1510** [bnb-chain/BEPs#162]
0x59576Fb376F1FEaEdb9c768A724D8C06304538f5

_Originally posted by @aasszzx707 in https://github.com/bnb-chain/BEPs/pull/132#discussion_r932488062_

**Comment by Arielek9** [comment]
Stopp

pon., 19 wrz 2022, 02:09 użytkownik Anastasia1510 ***@***.***>
napisał:
