### ISSUE TITLE
How do I increase the token amount?

### ISSUE THREAD

**Issue by furkandamar** [bnb-chain/BEPs#168]
I created BEP20 token via remix, now I want to increase this token amount. How can I make 100 thousand tokens 200 thousand?

**Comment by isaacyuno** [comment]
If you are using openzeppelin-contracts, you could call utilize the _mint function, or you could implement similar logic by yourself, like:
   function _mint(address to, uint value) internal {
        totalSupply = totalSupply.add(value);
        balanceOf[to] = balanceOf[to].add(value);
        emit Transfer(address(0), to, value);
    }
