### ISSUE TITLE
How to use binance Smart chain faucet

### ISSUE THREAD

**Issue by Execessmoney** [bnb-chain/BEPs#170]
Please how to use binance Smart chain faucet

**Comment by isaacyuno** [comment]
Only testnet has a faucet https://testnet.binance.org/faucet-smart

**Comment by valeolla** [comment]
Jak je možné, že se ani do MetaMusk ani do TrustWalet ten testovací BNB nepropsal?
Děkuji moc

**Comment by Mherjee18** [comment]
> Please how to use binance Smart chain faucet

**Comment by Ramyromel** [comment]
ندخل نعمل إيداع . تحديد عمله bnb . اختيار اول محفظه 
نعمل copy وندخل الموقع https://testnet.binance.org/faucet-smart
الخانه الفارغه paste وتضغط تأكيد

**Comment by zzzckck** [comment]
https://www.bnbchain.org/en/testnet-faucet
