### ISSUE TITLE
To address the ChiToken on BSC, like EIP-3529

### ISSUE THREAD

**Issue by brilliant-lx** [bnb-chain/BEPs#197]
BSC does not address the ChiToken yet, may need to solve it.
Ethereum has solved it in London Upgrade, with EIP-3529.
may refer:  https://github.com/ethereum/EIPs/blob/master/EIPS/eip-3529.md

**Comment by bnb-twu** [comment]
I will assign the task of implementing EIP-3529 into the BSC node.

**Comment by Przezrz** [comment]
> BSC does not address the ChiToken yet, may need to solve it. Ethereum has solved it in London Upgrade, with EIP-3529. may refer: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-3529.md
