### ISSUE TITLE
To address the 1 GWei Gas Price issue

### ISSUE THREAD

**Issue by brilliant-lx** [bnb-chain/BEPs#198]
Currently, most of the validators only accept gas price >=5Gwei, but some validator may not follow this rule.
The Gas Price is not part of the consensus yet, may need to dive deep and discuss within the community to see if it is necessary to add it as part of the consensus.

**Comment by 48ClubIan** [comment]
Really ?
Put the minimum gasprice in consensus ? 
It will make BNB Chain a unique masterpiece.

**Comment by 6639** [comment]
Who says it has to be greater than 5Gwei?
Are you kidding me?

**Comment by Roshanyu** [comment]
sb

**Comment by asiawildboar** [comment]
sb

**Comment by wangtsiao** [comment]
Why? Market supply and demand determine the price. If you hope higher price, then just develop more users.

**Comment by jasonthewhale** [comment]
STFU, you and CZ deserve a jail.

**Comment by brilliant-lx** [comment]
> Since when only accepting-above-5gwei is a RULE for validators to follow ?

There is no rule for it right now.
`GasPrice` is a critical part of the network, Ethereum uses BaseFee to adjust the price dynamically, BSC does not have BaseFee yet. I will close it, as it is a big topic, many need more cautious words to avoid misunderstanding.
