### ISSUE TITLE
When will you start supporting EIP-4337

### ISSUE THREAD

**Issue by BillInUK** [bnb-chain/BEPs#337]
When will you start supporting EIP-4337 & EIP1559?

**Comment by rondales** [comment]
> When will you start supporting EIP-4337 & EIP1559?

**Comment by rondales** [comment]
> When will you start supporting EIP-4337 & EIP1559?

**Comment by rondales** [comment]
> > When will you start supporting EIP-4337 & EIP1559?

**Comment by rondales** [comment]
https://github.com/bnb-chain/BEPs/issues/337#issuecomment-1855214942
