### ISSUE TITLE
Let's change the lingo here

### ISSUE THREAD

**Issue by Magkoohp** [bnb-chain/BEPs#356]
Let's change the lingo here

_Originally posted by @arein in https://github.com/WalletConnect/walletconnect-docs/pull/1448#pullrequestreview-1891223475_

**Comment by 199518** [comment]
https://github.com/https://github.com/users/199518/emails/309933454/confirm_verification/44367755?via_launch_code_email=true

**Comment by 199518** [comment]
https://github.com/enterprises/mohsin
