### ISSUE TITLE
docs: need to upgrade bnbchain doc links(GreenField)

### ISSUE THREAD

**Issue by zzzckck** [bnb-chain/BEPs#387]
GreenField doc site will be moved from: https://docs.bnbchain.org/greenfield-docs/ to https://docs.bnbchain.org/bnb_greenfield/
Several BEPs need to be updated accordingly.
List:
https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-293.md
https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-335.md
https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-346.md
https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-364.md
https://github.com/bnb-chain/BEPs/blob/master/BEPs/BEP-366.md

**Comment by zzzckck** [comment]
fixed in: https://github.com/bnb-chain/BEPs/pull/390

**Comment by jansonu** [comment]
[V1718721362943588(url)

**Comment by jansonu** [comment]
[]V1718721362943588
