### ISSUE TITLE
BNB

### ISSUE THREAD

**Issue by TeckChuanR** [bnb-chain/BEPs#393]
I need someone help me to change my assets
from BEPS to BSC !

**Comment by TeckChuanR** [comment]
I'm not familiar with Binance, can someone help me
and solve ?

**Comment by zzzckck** [comment]
What does it mean? from BEPS to BSC? Are your asset in BNB BeaconChain and you wanna to migrate it to BSC? @TeckChuanR

**Comment by Rubens1969** [comment]
***@***.***
