### ISSUE TITLE
Make money 

### ISSUE THREAD

**Issue by 122obi** [bnb-chain/BEPs#394]
This life is all about money that's all I have to say

**Comment by 122obi** [comment]
Money is All you need

**Comment by alialobidm** [comment]
[](url)

**Comment by kiko1842** [comment]
> This life is all about money that's all I have to say

Oh no actually ,I rather eat 3x a day than thinking money.
Just sig  up .

**Comment by Iho82** [comment]
Que debo hacer exactamente?
