### ISSUE TITLE
The description of delegation and undelegation in BEP-294 conflicts with the information in the latest documentation.

### ISSUE THREAD

**Issue by Spongebob-bear** [bnb-chain/BEPs#398]
# Problems
In BEP-294, Sections 5.2.2.1 and 5.2.2.2 state: “If users stake bnbAmount, the amount of credit mint to them is: stCreditAmount = bnbAmount * totalSupply() / totalPooledBNB. If users decide to unstake their stCreditAmount, they will be able to reclaim the equivalent amount of BNB, which will be exactly: (stCreditAmount * totalPooledBNB) / totalSupply(). ”

However, in the latest documentation (https://docs.bnbchain.org/bnb-smart-chain/validator/overview/#what-is-validator), it is mentioned that a commission fee must be extracted from what all delegators get, but this commission fee is not reflected in the above equations provided in BEP-294.

I am seeking clarification on which description is correct. Specifically, how does BSC compute the BNB an undelegator finally receives, considering the commission fee?

**Comment by Spongebob-bear** [comment]
Hi @zzzckck,
Could you please help clarify the conflict between the delegation and undelegation descriptions in BEP-294 and the latest documentation? Your assistance would be greatly appreciated.

Thank you in advance for your help!

**Comment by unclezoro** [comment]
hi @Spongebob-bear  I believe our understanding of the commission fee may differ.  You might think that the commission fee comes from the user's delegation, that's not the case, the commission fee comes from the block rewards. For example, there are 10 delegator, each staking 1BNB, and commision rate is 10%, and one day the validator receive 1 bnb block rewards, then the value of a delegator is:   1BNB * (1 - 10% commission rate)  * ( 1BNB user delegation / 10 BNB totoal delegation) + 1 BNB user delegation =  1.09 BNB

**Comment by Spongebob-bear** [comment]
> hi @Spongebob-bear I believe our understanding of the commission fee may differ. You might think that the commission fee comes from the user's delegation, that's not the case, the commission fee comes from the block rewards. For example, there are 10 delegator, each staking 1BNB, and commision rate is 10%, and one day the validator receive 1 bnb block rewards, then the value of a delegator is: 1BNB * (1 - 10% commission rate) * ( 1BNB user delegation / 10 BNB totoal delegation) + 1 BNB user delegation = 1.09 BNB. In another word, the value of user delegation will never decrease, only possible increase.

Thank you for your response, it resolves my question!

**Comment by Spongebob-bear** [comment]
> hi @Spongebob-bear I believe our understanding of the commission fee may differ. You might think that the commission fee comes from the user's delegation, that's not the case, the commission fee comes from the block rewards. For example, there are 10 delegator, each staking 1BNB, and commision rate is 10%, and one day the validator receive 1 bnb block rewards, then the value of a delegator is: 1BNB * (1 - 10% commission rate) * ( 1BNB user delegation / 10 BNB totoal delegation) + 1 BNB user delegation = 1.09 BNB. In another word, the value of user delegation will never decrease, only possible increase.

Thank you for your response, it resolves my question!
