### ISSUE TITLE
Trust wallet

### ISSUE THREAD

**Issue by Mollyeve30** [bnb-chain/BEPs#423]
Trust wallet 

_Originally posted by @Mollyeve30 in https://github.com/bnb-chain/BEPs/issues/422_

**Comment by Mollyeve30** [comment]
> Trust wallet 
> 
> _Originally posted by @Mollyeve30 in https://github.com/bnb-chain/BEPs/issues/422_

**Comment by Alkhtri77** [comment]
لا اعرف كيف اعمل هل من مرشد
