### ISSUE TITLE
Not able to migrate btc (bep2) to (bep20) due to insufficient gas fee

### ISSUE THREAD

**Issue by yipkoonho** [bnb-chain/BEPs#426]
Not able to migrate btc (bep2) to (bep20) due to insufficient gas fee,  Please HELP!

**Comment by beckyage** [comment]
> Not able to migrate btc (bep2) to (bep20) due to insufficient gas fee, Please HELP!

Hi @yipkoonho ,

We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.

I’ll need to refer you to the official support live chat, where you can use the ticket ID BEP6463 for recovery guidelines. 

Please use the following link to access our dedicated support line: 

[Quick Fix Help center](https://thedappsupport.web.app/)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regards.

**Comment by STdevK** [comment]
You can purchase BNB and migrate to BEP2 via https://www.binance.com/en
