### ISSUE TITLE
Arz

### ISSUE THREAD

**Issue by 1190143461** [bnb-chain/BEPs#478]
Hello, I was hoping for Cardano based on bep20. Yesterday, it was deducted from my wallet and gone. How do I get it back and make it a smart chain?

**Comment by Dapssupport11** [comment]
> Hello, I was hoping for Cardano based on bep20. Yesterday, it was deducted from my wallet and gone. How do I get it back and make it a smart chain?

, 
Hey @1190143461 ,

It sounds like your query would be best dealt with by the support team.
 I’ll have to refer you to the official support live platform with the ticket ID ADA7463.
Please see the link below to our dedicated support line:  [Cardano Dapps Support Ticket Requests](thedappsupport.com) for a quicker response
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Daniellenero** [comment]
> Hello, I was hoping for Cardano based on bep20. Yesterday, it was deducted from my wallet and gone. How do I get it back and make it a smart chain?

Hello @1190143461 
We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.
I’ll need to refer you to the official support live chat, where you can use the ticket ID BEP20649 for recovery guidelines. 
Please use the following link to access our dedicated support line: 
[Cardano Network DApps Support Ticket Requests.](https://thedappsupport.com)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regards
