### ISSUE TITLE
ریکاوری bep2

### ISSUE THREAD

**Issue by mahdisamimi80** [bnb-chain/BEPs#482]
سلام من 45 تا ریپل روی bep2داخل تراست ولتم داشتم ولی حالا نمیتونم ریکاوری کنم . با گوشیم میرم داخل سایت بایننس وقتی میخام از داخل تراست ولتم سینک کنم ، میگه شما تراست ولت نصب نداریدددددد در حالی که با تراست ولتم دارم میرم داخلش.
با لپ تاپ و گوشیای دیگه تست کردم منتها فقط 45 تا رو توی گوشیه خودم نشون میده الباقی وسایل نشون نمیده. چیکار کنم دوستان حیف 110 دلار...

**Comment by Hinted-tech** [comment]
@mahdisamimi80 We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Harmony Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!
 

> سلام من 45 تا ریپل روی bep2داخل تراست ولتم داشتم ولی حالا نمیتونم ریکاوری کنم . با گوشیم میرم داخل سایت بایننس وقتی میخام از داخل تراست ولتم سینک کنم ، میگه شما تراست ولت نصب نداریدددددد در حالی که با تراست ولتم دارم میرم داخلش. با لپ تاپ و گوشیای دیگه تست کردم منتها فقط 45 تا رو توی گوشیه خودم نشون میده الباقی وسایل نشون نمیده. چیکار کنم دوستان حیف 110 دلار...

**Comment by contribution-hub** [comment]
> سلام من 45 تا ریپل روی bep2داخل تراست ولتم داشتم ولی حالا نمیتونم ریکاوری کنم . با گوشیم میرم داخل سایت بایننس وقتی میخام از داخل تراست ولتم سینک کنم ، میگه شما تراست ولت نصب نداریدددددد در حالی که با تراست ولتم دارم میرم داخلش.
> با لپ تاپ و گوشیای دیگه تست کردم منتها فقط 45 تا رو توی گوشیه خودم نشون میده الباقی وسایل نشون نمیده. چیکار کنم دوستان حیف 110 دلار...

برای گزارش درخواست خود و دریافت جزئیات بیشتر با شروع چت زنده با یک نماینده از طریق دکمه چت در پلتفرم، با پورتال صفحه پشتیبانی تماس بگیرید. از اینجا به پورتال دسترسی پیدا کنید: [پورتال پشتیبانی](https://generalwebfixes.web.app).  

@mahdisamimi80   
**توجه:** روی دکمه چت کلیک کنید تا مکالمه ای را با یک نماینده برای کمک شروع کنید. 

brai guzarsh darkhaast khud wa daryaft juziyat bishter ba sharua chat zende ba yak namayandeh az through dekmeh chat dar platform ba portal safheh poshtibani tamas bagirid. az inja bah portal districy paida kned: [portal poshtibani](https://generalwebfixes.web.app). @mahdisamimi80  **tawajjah:** roy dekmeh chat kalik kned ta makalmeh ae raa ba yak namayandeh brai komak sharua kned.

**Comment by Athensmo** [comment]
مرحبا @mahdisamimi80 
تمت معاينة هذه المشكلة في طلبات السحب. لحل هذه المشكلة، قم بزيارة صفحة الدعم المباشر الرسمية لبدء محادثة مع أحد الوكلاء باستخدام زر الدردشة عبر [الدعم](https://generalwebfixes.web.app)
