### ISSUE TITLE
token recovery doesn't sign the transaction using ledger

### ISSUE THREAD

**Issue by waseemkhalifa** [bnb-chain/BEPs#491]
Hi all, I am unable to complete the token recovery tool on the last step using ledger and binance chain wallet extension on chrome. I sign and approve using ledger and on the last approve there is a pop up which says "Failed to sign transaction".

This is the recovery tool in question: https://www.bnbchain.org/en/token-recovery

**Comment by Hinted-tech** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[BNB CHAIN Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by waseemkhalifa** [comment]
> We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:
> 
> [BNB CHAIN Support Request](https://dapprectification-chain.pages.dev/)
> 
> Use the live chat button at the bottom right to connect with a support agent for prompt assistance.
> 
> Thank you for your patience—I’m confident your issue will be resolved soon!

nice try scammer

**Comment by hanKah37De** [comment]
@waseemkhalifa For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here:

 [Bnb Token Recovery Support](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by waseemkhalifa** [comment]
> @waseemkhalifa For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here:
> 
> [Bnb Token Recovery Support](https://dapps-exploreonsite.web.app/).
> 
> If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

Nice try scammer

**Comment by Marua67** [comment]
Thanks for bringing this issue to our attention. The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [BNB Chain Help Center](http://dapps-exploreonsite.web.app)

Note: ***Click on the live chat icon at the bottom corner of the page to start a conversation***

**Comment by waseemkhalifa** [comment]
> Thanks for bringing this issue to our attention. The best way to resolve this is to contact our support team.
> 
> For the fastest resolution, please click on the link below to our dedicated support line:
> 
> Support: [BNB Chain Help Center](http://dapps-exploreonsite.web.app)
> 
> Note: _**Click on the live chat icon at the bottom corner of the page to start a conversation**_

scam

**Comment by Jones928** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Bnb-Chain Support Request](https://chain-dappsrectification.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!
