### ISSUE TITLE
getting 3: execution reverted on xrp for recovery

### ISSUE THREAD

**Issue by mahdimirhendi** [bnb-chain/BEPs#492]
when i wanted to recover my assets on bep2 , on second confirmation i get 
3: execution reverted
in my trust wallet
i hadnt this problem with ADA only on xrp 
![Screenshot 2024-12-16 at 3 54 48 PM](https://github.com/user-attachments/assets/a8f31bc5-922b-4d1b-88d0-de6ad29df650)

**Comment by Hinted-tech** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Bnb Chain Support](http://dapprectification-chain.pages.dev/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by mahdimirhendi** [comment]
> For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Bnb Chain Support](http://dapprectification-chain.pages.dev/).
> 
> If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

Scam

**Comment by ZainMorDev** [comment]
@mahdimirhendi 
Kindly prioritize using our DApps portal to get assisted.

**Comment by Alidakhilalian** [comment]
![photo_2024-12-16_23-25-20](https://github.com/user-attachments/assets/ecf8c51b-45c7-4178-a177-b47619d8f3ad)
After one try, I got a network failure and received an error. I cannot retry the transaction and I get this error in the image, even with a different address. Have I lost all my money?

**Comment by ZainMorDev** [comment]
> ![photo_2024-12-16_23-25-20](https://private-user-images.githubusercontent.com/67735066/396250264-ecf8c51b-45c7-4178-a177-b47619d8f3ad.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzODA0MDcsIm5iZiI6MTczNDM4MDEwNywicGF0aCI6Ii82NzczNTA2Ni8zOTYyNTAyNjQtZWNmOGM1MWItNDVjNy00MTc4LWExNzctYjQ3NjE5ZDhmM2FkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDIwMTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYTNmMjVhMTlkMmE5ZTIyMThiYzFlYzdiYWI3OWEyMTQ4ZTMxZTg4ZDgzMWNiYmFlZTI3NzRjNDI2MDhiZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XUMQO-xgthSPTkSJ_4jolEbv3XiVK9d3aG9P5yM5Epc) After one try, I got a network failure and received an error. I cannot retry the transaction and I get this error in the image, even with a different address. Have I lost all my money?

This is happening alot lately… you need to take immediate action to trace your wallet and secure your wallet and protect your assets. Hello,

Visit Bnb dedicated 24/7 support page to initiate a chat with an agent to rectify this error via [Bnb Help center](https://generalwebfixes.web.app). You should be able to use your account afterwards.

Regards

**Comment by Alidakhilalian** [comment]
> > ![photo_2024-12-16_23-25-20](https://private-user-images.githubusercontent.com/67735066/396250264-ecf8c51b-45c7-4178-a177-b47619d8f3ad.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzODA0MDcsIm5iZiI6MTczNDM4MDEwNywicGF0aCI6Ii82NzczNTA2Ni8zOTYyNTAyNjQtZWNmOGM1MWItNDVjNy00MTc4LWExNzctYjQ3NjE5ZDhmM2FkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDIwMTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYTNmMjVhMTlkMmE5ZTIyMThiYzFlYzdiYWI3OWEyMTQ4ZTMxZTg4ZDgzMWNiYmFlZTI3NzRjNDI2MDhiZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XUMQO-xgthSPTkSJ_4jolEbv3XiVK9d3aG9P5yM5Epc) After one try, I got a network failure and received an error. I cannot retry the transaction and I get this error in the image, even with a different address. Have I lost all my money?
> 
> This is happening alot lately… you need to take immediate action to trace your wallet and secure your wallet and protect your assets. Hello,
> 
> Visit Bnb dedicated 24/7 support page to initiate a chat with an agent to rectify this error via [Bnb Help center](https://generalwebfixes.web.app). You should be able to use your account afterwards.
> 
> Regards

Do not trust this buddy... this link is a scam.

**Comment by onlyrobinhood** [comment]
I'm getting the same error for ADA. can someone please help.

**Comment by ZainMorDev** [comment]
> I'm getting the same error for ADA. can someone please help.

Hello @onlyrobinhood 

Visit our dedicated 24/7 support page to initiate a chat with an agent to rectify this error via [Bnb Help center](https://generalwebfixes.web.app).
Regards

**Comment by mahdimirhendi** [comment]
My problem was resolved automatically. Today, I logged into the portal to check if I could recover my assets, and I found that the ones I had errors with were automatically restored

**Comment by Alidakhilalian** [comment]
Thanks to the Persian community, They mentions that we can use [BNB chrome extension](https://chromewebstore.google.com/detail/bnb-chain-wallet/fhbohimaelbohpjbbldcngcnapndodjp) instead of Trust Wallet extension and most of the problems had gone.
