### ISSUE TITLE
  BEP2

### ISSUE THREAD

**Issue by Roza1338** [bnb-chain/BEPs#493]
Здравствуте, не могу вывести FTM из сети BEP2

**Comment by ZainMorDev** [comment]
Hello @Roza1338 

Посетите нашу специальную страницу круглосуточной поддержки, чтобы начать чат с агентом и исправить эту ошибку через [Справочный центр Bnb](https://generalwebfixes.web.app). С уважением

**Comment by waseemkhalifa** [comment]
> Hello @Roza1338
> 
> Посетите нашу специальную страницу круглосуточной поддержки, чтобы начать чат с агентом и исправить эту ошибку через [Справочный центр Bnb](https://generalwebfixes.web.app). С уважением

scam
