### ISSUE TITLE
BEP

### ISSUE THREAD

**Issue by thanhvietmkb123456789** [bnb-chain/BEPs#495]

**Comment by Ddaylit** [comment]
Hello there, 

Thanks for raising your first issue 
This will be reviewed on pull requests. 

We use GitHub issues as a place to track bugs and other development-related issues.
It might take couple of days before we can provide a reply on here. 
I’d recommend you contact to the official support website to initiate a chat with the official support via [Bnb live support](https://generalwebfixes.web.app/) to complete your request.

**Comment by Ddaylit** [comment]
Remember to include a link to this issue in your chat to aid easy resolution

**Comment by thanhvietmkb123456789** [comment]
![Uploading 446898923_770675481800846_1044067117075215079_n.jpg…]()

**Comment by Ddaylit** [comment]
Hi @thanhvietmkb123456789, what image are you trying to upload?
